services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./publisher.py:/app/main.py
    ports:
      - 5555:5555
    deploy:
      replicas: 1

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./subscriber.py:/app/main.py
    deploy:
      replicas: 1
