services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - 5555:5555
      - 5556:5556

  servidor:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./servidor.py:/app/main.py
    depends_on:
      - broker
    deploy:
      replicas: 1

  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./cliente.py:/app/main.py
    depends_on:
      - servidor
    deploy:
      replicas: 1
